runtime: nodejs22
env: standard

handlers:
  - url: /(.*\.(css|js|map|png|jpg|jpeg|gif|svg|ico|webp|woff|woff2|ttf|eot))$
    static_files: www/\1
    upload: www/(.*\.(css|js|map|png|jpg|jpeg|gif|svg|ico|webp|woff|woff2|ttf|eot))$

  - url: /.*
    static_files: www/index.html
    upload: www/index.html
