steps:
  - name: 'node:22'
    entrypoint: npm
    args: ['install']

  - name: 'node:22'
    entrypoint: npm
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

timeout: '900s'
options:
  logging: CLOUD_LOGGING_ONLY
